[package]
name = "textwrap"
version = "0.12.1"
authors = ["Martin Geisler <martin@geisler.net>"]
description = """
Textwrap is a library for word wrapping, indenting, and dedenting
strings.

You can use it to format strings (such as help and error messages) for
display in commandline applications. It is designed to be efficient
and handle Unicode characters correctly.
"""
documentation = "https://docs.rs/textwrap/"
repository = "https://github.com/mgeisler/textwrap"
readme = "README.md"
keywords = ["text", "formatting", "wrap", "typesetting", "hyphenation"]
categories = ["text-processing", "command-line-interface"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "mgeisler/textwrap" }
appveyor = { repository = "mgeisler/textwrap" }
codecov = { repository = "mgeisler/textwrap" }

[dependencies]
unicode-width = "0.1"
terminal_size = { version = "0.1", optional = true }
hyphenation = { version = "0.8", optional = true, features = ["embed_en-us"] }

[dev-dependencies]
lipsum = "0.6"
rand = "0.6"
rand_xorshift = "0.1"
version-sync = "0.9"
criterion = "0.3"

[target.'cfg(unix)'.dev-dependencies]
termion = "1.5"

